### ISSUE TITLE
teleport_absolute only work for x = 0 and y = 0 in turtlesim

### ISSUE THREAD

**Issue by USeebi** [Affonso-Gui/scratch3-ros#3]
Tried the operation with Scratch blocks enclosed.  No matter what x, y locations set, the turtle always ended up at (0, 0). What did I miss?

![image](https://github.com/Affonso-Gui/scratch3-ros/assets/22373557/dda3f9c1-dda5-45e2-8c06-b6cd6d6baea9)

**Comment by Affonso-Gui** [comment]
Hello,

1. Are any messages being published to `turtle1/pose`?
If not, the code will stop at `Get message from [topic]`, so the `go to x: [val] y: [val]` won't be reached.
2. Are you getting any error messages in the console? Usually you can open it with F12.
3. If none of the above applies, would you mind sharing the project file (or a part of it) so I could have a look?

**Comment by USeebi** [comment]
1. I'm confused, did u mean Set pose x and Set pose y for teleport_absolute?
2. I don't have any error from the Console while teleport_absolute executed.
3. Enclosed my sb3 project file.
[turtleMaze.zip](https://github.com/Affonso-Gui/scratch3-ros/files/15387567/turtleMaze.zip)

**Comment by Affonso-Gui** [comment]
> I'm confused, did u mean Set pose x and Set pose y for teleport_absolute?

Sorry, was looking in the wrong place..

There seems to be an error with the message type. Try to send `pose` (not `res`) to the service call, and check for errors in the rosbridge terminal.

**Comment by USeebi** [comment]
Thanks Affonso but changed to Send pose seems no help, I guess pose & res are the same type of variable container in Scratch.  I also don't have any error from the rosbridge terminal.

How could we check what exactly is sent from Scratch to the ROS server?

**Comment by USeebi** [comment]
I figured out why it didn't help by send pose (not res) to the service call, if I use pose only without including cmd_vel the service call resulted in an error as attached.

My workaround is to use res with join parameters from pose & cmd_vel and I also managed to have locations other than x = 0 & y = 0 by setting res first before the x & Y locations.

But is this a bug to have linear_velocity or linear.x to call teleport_absolute service?


![pose_error](https://github.com/Affonso-Gui/scratch3-ros/assets/22373557/c06b1507-232f-49c2-9faf-984ddeed4def)

**Comment by Affonso-Gui** [comment]
Sorry for the delay.

I am attaching a fix for what I think is what you wanted to do.


![Screenshot 2024-06-08 115000](https://github.com/Affonso-Gui/scratch3-ros/assets/20625381/d9f2c48c-7e7a-441d-a51e-f53777369157)

A little more explanation about message types in scratch3-ros:
- Differently from the ROS itself, the scratch3-ros interface is loosely typed (this is a limitation from the roslibjs library we are using within the project)
- All messages end up being sent as json objects
- When the expected message type does not match the received type, the following happens:
  - The receiver will fill up any missing fields with the default values
  - If there are any additional fields, the rosbridge will refuse to send the message and issue an error


In the above example:
- The expected service type for teleport_absolute is:
```bash
$ rossrv show turtlesim/TeleportAbsolute
float32 x
float32 y
float32 theta
---
```
- This translates to a json object like the following:
```json
{"x":10, "y":10, "theta": 0}
```
- In the provided snippet, `res` will be set to something like the following. Since this is not a valid json object, the default value (filled with zeros) is used.
```json
{"x":10, "y":10, "theta": -2.5, "linear_velocity":0, "angular_velocity":0}{"linear":{"x":2}}
```
- As a general rule, the `join` is made for string concatenation, so avoid it for manipulating json objects


> But is this a bug to have linear_velocity or linear.x to call teleport_absolute service?

Unfortunately yes (the rosbridge will refuse to send the message).

[turtleMaze_fix.zip](https://github.com/user-attachments/files/15746281/turtleMaze_fix.zip)

**Comment by USeebi** [comment]
Thanks Affonso,

I guess the bug is fixed as the error on "does not have a field linear-Velocity" is gone. Is there any update on the codes?

**Comment by Affonso-Gui** [comment]
No updates in the scratch3-ros code.
For the good and for the bad the above behavior is expected.

**Comment by USeebi** [comment]
no problem an the issue is closed.
